# Generated by Django 5.2.6 on 2025-10-09 20:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ConferenceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('submission_id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Le nom de la salle ne doit contenir que des lettres et des chiffres.', regex='^[A-Za-z0-9]+$')])),
                ('topic', models.CharField(max_length=255)),
                ('session_day', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('keywords', models.CharField(max_length=255)),
                ('submission_date', models.DateField()),
                ('paper', models.FileField(upload_to='papers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='ConferenceApp.conference')),
            ],
        ),
    ]
