# Generated by Django 5.2.6 on 2025-10-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SessionApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='submission_id',
            new_name='session_id',
        ),
    ]
