# Generated by Django 5.2.6 on 2025-10-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionApp', '0002_rename_submission_id_session_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
