# Generated by Django 5.2.6 on 2025-10-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionApp', '0004_alter_session_end_time_alter_session_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
