# Generated by Django 5.2.6 on 2025-10-15 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0002_initial'),
        ('SessionApp', '0005_alter_session_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='ConferenceApp.conference'),
        ),
    ]
