# Generated by Django 5.2.6 on 2025-10-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0005_alter_submission_user'),
    ]

    operations = [
    ]
